myproject/crm/urls.py
from django.urls import path
from myproject.crm import views as c

app_name = 'crm'

urlpatterns = [
    path('customer/', c.CustomerList.as_view(), name='customer_list'),
    path('customer/add/', c.CustomerCreate.as_view(), name='customer_add'),
    path('customer/<int:pk>/', c.CustomerDetail.as_view(), name='customer_detail'),
    path(
        'customer/<int:pk>/edit/',
        c.CustomerUpdate.as_view(),
        name='customer_update'
    ),
    path(
        'customer/<int:pk>/delete/',
        c.customer_delete,
        name='customer_delete'
    ),
]

myproject/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('myproject.core.urls')),
    path('accounts/', include('myproject.accounts.urls')),
    path('crm/', include('myproject.crm.urls')),
    path('admin/', admin.site.urls),
]

myproject/crm/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse, reverse_lazy
from myproject.core.models import TimeStampedModel, Address, Document, Active
from myproject.utils.lists import PHONE_TYPE, PERSON_TYPE, DEPARTMENT
from .managers import PersonManager, CustomerManager


class People(TimeStampedModel, Address, Document, Active):
    ''' Tabela base de pessoas '''
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    slug = models.SlugField()
    photo = models.ImageField('foto', null=True, blank=True)
    birthday = models.DateField('nascimento', null=True, blank=True)
    department = models.CharField(
        'departamento',
        max_length=3,
        choices=DEPARTMENT,
        null=True,
        blank=True
    )
    info = models.TextField('informações', null=True, blank=True)

    class Meta:
        abstract = True
        ordering = ('user__first_name',)

    def __str__(self):
        return self.user.get_full_name()

    full_name = property(__str__)


class Person(People):
    person_type = models.CharField(
        'usuário, cliente ou fornecedor',
        max_length=1,
        choices=PERSON_TYPE,
        default='u'
    )
    occupation = models.ForeignKey(
        'Occupation',
        verbose_name='cargo',
        related_name='person_occupation',
        on_delete=models.CASCADE,
        null=True,
        blank=True
    )

    objects = PersonManager()

    def get_absolute_url(self):
        pass
        # return r('crm:person_detail', slug=self.slug)


class Phone(models.Model):
    phone = models.CharField('telefone', max_length=20, null=True, blank=True)
    person = models.ForeignKey(
        'Person',
        on_delete=models.CASCADE,
        related_name='persons'
    )
    phone_type = models.CharField(
        'tipo',
        max_length=3,
        choices=PHONE_TYPE,
        default='pri'
    )


class Customer(Person):
    objects = CustomerManager()

    class Meta:
        proxy = True
        verbose_name = 'cliente'
        verbose_name_plural = 'clientes'

    def get_absolute_url(self):
        return reverse_lazy('crm:customer_detail', kwargs={'pk': self.pk})

    @property
    def list_url(self):
        return reverse('crm:customer_list')

    @property
    def update_url(self):
        if self.pk:
            kw = {'pk': self.pk}
            return reverse_lazy('crm:customer_update', kwargs=kw)
        return None

    @property
    def delete_url(self):
        if self.pk:
            kw = {'pk': self.pk}
            return reverse_lazy('crm:customer_delete', kwargs=kw)
        return None

    # def save(self, *args, **kwargs):
    #     # Update person_type
    #     self.person_type = 'c'
    #     super(Customer, self).save(*args, **kwargs)


class Occupation(models.Model):
    occupation = models.CharField('cargo', max_length=50, unique=True)

    class Meta:
        ordering = ('occupation',)
        verbose_name = 'cargo'
        verbose_name_plural = 'cargos'

    def __str__(self):
        return self.occupation

myproject/crm/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.template.defaultfilters import slugify
from .models import Customer


# class UserAdminCreationForm(UserCreationForm):
# Sem senha definida
class UserAdminCreationForm(forms.ModelForm):
    ''' Cadastro geral de User '''
    first_name = forms.CharField(label='Nome')
    last_name = forms.CharField(label='Sobrenome')
    email = forms.EmailField(label='E-mail')

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email')

    def clean_email(self):
        email = self.cleaned_data['email']
        # username = email
        self.cleaned_data['username'] = email
        return email

    def save(self, commit=True):
        instance = super(UserAdminCreationForm, self).save(commit=False)
        # Salva username = email
        instance.username = self.cleaned_data['email']
        if commit:
            instance.save()
            # Cria Customer
            create_customer(instance)
        return instance


def create_customer(instance):
    # Salva slug
    fullname = '{} {}'.format(
        instance.first_name,
        instance.last_name
    )
    if fullname.strip():
        slug = slugify(fullname)
    else:
        slug = slugify(instance.email)
    # Cria Customer
    customer, _ = Customer.objects.get_or_create(
        user=instance,
        slug=slug,
        person_type='c'
    )


class CustomerUpdateForm(forms.ModelForm):
    slug = forms.SlugField(disabled=True)

    class Meta:
        model = Customer
        fields = (
            'slug',
            'photo',
            'cpf',
            'rg',
            'cnpj',
            'ie',
            'birthday',
            'department',
            'info',
            'occupation',
            'address',
            'address_number',
            'complement',
            'district',
            'city',
            'uf',
            'cep',
        )

myproject/crm/views.py
from django.contrib.auth.models import User
from django.contrib.messages.views import SuccessMessageMixin
from django.shortcuts import HttpResponseRedirect
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, UpdateView
from myproject.core.actions import _delete
from myproject.core.mixins import ActiveMixin
from .models import Customer
from .forms import UserAdminCreationForm, CustomerUpdateForm
from .mixins import SuccessUrlMixin


def customer_delete(request, pk):
    _delete(Customer, pk)
    return HttpResponseRedirect(reverse_lazy('crm:customer_list'))


class CustomerList(ActiveMixin, ListView):
    model = Customer


class CustomerDetail(DetailView):
    model = Customer


class CustomerCreate(SuccessUrlMixin, CreateView):
    model = User
    form_class = UserAdminCreationForm
    template_name = 'crm/customer_form.html'
    model_name = Customer
    my_success_url = 'crm:customer_update'


class CustomerUpdate(UpdateView):
    model = Customer
    form_class = CustomerUpdateForm
    template_name = 'crm/customer_form.html'
    success_url = reverse_lazy('crm:customer_list')

myproject/crm/templates/crm/customer_detail.html
{% extends "base.html" %}

{% block title %}
  Clientes
{% endblock title %}

{% block breadcrumb %}
  {% include "includes/breadcrumb_detail.html" %}
{% endblock breadcrumb %}

{% block content %}

<div class="row">
  <div class="col-md-12">
    <div class="card">
      <div class="card-header">
        Detalhes
        <a href="{{ object.update_url }}" class="btn" title="Editar">
          <i class="fa fa-pencil-square-o" aria-hidden="true"></i>
        </a>
        <a href="#ModalDelete" class="btn" role="button" data-toggle="modal" title="Apagar">
          <i class="fa fa-trash" aria-hidden="true"></i>
        </a>
      </div>
      <div class="card-body">
        <div class="card-columns">
          <div class="card">
            <img class="card-img-top" data-src="holder.js/100px180/?text=Image cap" alt="Image cap [100%x180]" src="data:image/svg+xml;charset=UTF-8,%3Csvg%20width%3D%22318%22%20height%3D%22180%22%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20viewBox%3D%220%200%20318%20180%22%20preserveAspectRatio%3D%22none%22%3E%3Cdefs%3E%3Cstyle%20type%3D%22text%2Fcss%22%3E%23holder_16050836ef6%20text%20%7B%20fill%3Argba(255%2C255%2C255%2C.75)%3Bfont-weight%3Anormal%3Bfont-family%3AHelvetica%2C%20monospace%3Bfont-size%3A16pt%20%7D%20%3C%2Fstyle%3E%3C%2Fdefs%3E%3Cg%20id%3D%22holder_16050836ef6%22%3E%3Crect%20width%3D%22318%22%20height%3D%22180%22%20fill%3D%22%23777%22%3E%3C%2Frect%3E%3Cg%3E%3Ctext%20x%3D%22109.140625%22%20y%3D%2297.2%22%3EImage%20cap%3C%2Ftext%3E%3C%2Fg%3E%3C%2Fg%3E%3C%2Fsvg%3E"
            data-holder-rendered="true" style="height: 180px; width: 100%; display: block;">
            <div class="card-body">
              <h4 class="card-title">{{ object.full_name }}</h4>
              <a href="mailto:{{ object.user.email }}" class="card-text">{{ object.user.email }}</a>
            </div>
            <ul class="list-group list-group-flush">
              <li class="list-group-item">RG: {{ object.rg }}</li>
              <li class="list-group-item">CPF: {{ object.cpf }}</li>
              <li class="list-group-item">{{ object.address }}</li>
            </ul>
            <div class="card-body">
              <a href="#" class="card-link">Card link</a>
              <a href="#" class="card-link">Another link</a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

{% include "modal/modal_delete.html" %}

{% endblock content %}

myproject/crm/templates/crm/customer_form.html
{% extends "base.html" %}
{% load widget_tweaks %}

{% block title %}
  Clientes
{% endblock title %}

{% block breadcrumb %}
  {% include "includes/breadcrumb_update.html" %}
{% endblock breadcrumb %}

{% block content %}

<div class="row">
  <div class="col-md-12">
    <div class="card">
      <div class="card-header">
        Cadastrar
      </div>
      <div class="card-body">
        <div class="col-sm-6">
          <form action="" method="POST">
            {% csrf_token %}
            {% for field in form.visible_fields %}
              <div class="form-group">
                <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                {% render_field field class="form-control" %}
                {% for error in field.errors %}
                  <span class="text-muted">{{ error }}</span>
                {% endfor %}
              </div>
            {% endfor %}
            <button type="submit" class="btn btn-sm btn-primary">Salvar</button>
          </form>

        </div>
      </div>
    </div>
  </div>
</div>

{% endblock content %}

{% block js %}

<script>
$(document).ready(function(){
  $('#id_birthday').datepicker({
    locale: "pt-BR"
  });
})
</script>

{% endblock js %}

myproject/crm/templates/crm/customer_list.html
{% extends "base.html" %}
{% load static %}

{% block title %}
  Clientes
{% endblock title %}

{% block breadcrumb %}
  {% include "includes/breadcrumb.html" %}
{% endblock breadcrumb %}

{% block content %}

<div class="row">
  <div class="col-md-12">
    <div class="card">
      <div class="card-header">
        Clientes
      </div>
      <div class="card-body">
        <div class="col-sm-12">
          <div class="">
            <div class="col-md-2">
              <a href="{% url 'crm:customer_add' %}" class="btn btn-success btn-block" style="margin: 0 0 5px 15px">
                <i class="fa fa-plus-square" aria-hidden="true"></i>
                <span>Adicionar</span>
              </a>
            </div>
            <div class="">
              <!-- { include "includes/search.html" %} -->
              <!-- <input type="text" class="search form-control" placeholder="Buscar"> -->
            </div>
          </div>
          <table id="table" class="table table-responsive-sm table-bordered table-striped">
            <thead class="thead-light">
              <tr>
                <th></th>
                <th>Nome</th>
                <th>E-mail</th>
                <th>Telefone</th>
                <th>Status</th>
              </tr>
            </thead>
            <tbody>
              {% for object in object_list %}
                <tr>
                  <td></td>
                  <td><a href="{{ object.get_absolute_url }}">{{ object.full_name }}</a></td>
                  <td>{{ object.user.email }}</td>
                  <td>{{ object.phone }}</td>
                  <td>
                    {% if object.active %}
                      <span class="badge badge-success">Ativo</span>
                    {% else %}
                      <span class="badge badge-secondary">Inativo</span>
                    {% endif %}
                    <div class="pull-right">
                      <a href="{{ object.update_url }}" class="btn btn-sm" title="Editar">
                        <i class="fa fa-pencil-square-o" aria-hidden="true"></i>
                      </a>
                      <a href="#ModalDelete" class="btn btn-sm object-delete" role="button" data-toggle="modal" data-object="{{ object }}" data-url="{{ object.delete_url }}" title="Apagar">
                        <i class="fa fa-trash" aria-hidden="true"></i>
                      </a>
                    </div>
                  </td>
                </tr>
              {% endfor %}
              <!-- <tr>
                <td></td>
                <td>Vishnu Serghei</td>
                <td>vishnu.serghei@email.com</td>
                <td>11 98765-4321</td>
                <td>
                  <span class="badge badge-success">Active</span>
                </td>
              </tr>
              <tr>
                <td></td>
                <td>Zbyněk Phoibos</td>
                <td>zbynek.phoibos@email.com</td>
                <td>11 98765-4321</td>
                <td>
                  <span class="badge badge-danger">Banned</span>
                </td>
              </tr>
              <tr>
                <td></td>
                <td>Einar Randall</td>
                <td>einar.randall@email.com</td>
                <td>11 98765-4321</td>
                <td>
                  <span class="badge badge-secondary">Inactive</span>
                </td>
              </tr>
              <tr>
                <td></td>
                <td>Félix Troels</td>
                <td>felix.troels@email.com</td>
                <td>11 98765-4321</td>
                <td>
                  <span class="badge badge-warning">Pending</span>
                </td>
              </tr>
              <tr>
                <td></td>
                <td>Aulus Agmundr</td>
                <td>aulus.agmundr@email.com</td>
                <td>11 98765-4321</td>
                <td>
                  <span class="badge badge-success">Active</span>
                </td>
              </tr> -->
            </tbody>
          </table>
          <!-- <nav>
            <ul class="pagination">
              <li class="page-item">
                <a class="page-link" href="#">Prev</a>
              </li>
              <li class="page-item active">
                <a class="page-link" href="#">1</a>
              </li>
              <li class="page-item">
                <a class="page-link" href="#">2</a>
              </li>
              <li class="page-item">
                <a class="page-link" href="#">3</a>
              </li>
              <li class="page-item">
                <a class="page-link" href="#">4</a>
              </li>
              <li class="page-item">
                <a class="page-link" href="#">Next</a>
              </li>
            </ul>
          </nav> -->
        </div>
      </div>
    </div>
  </div>
</div>

{% include "modal/modal_delete.html" %}

{% endblock content %}

{% block js %}

<script src="{% static 'js/modal.js' %}"></script>

<script>
  $(document).ready(function() {
    $('#table').DataTable({
      language: {
        "url": "//cdn.datatables.net/plug-ins/1.10.16/i18n/Portuguese-Brasil.json"
      },
      columnDefs: [{
        orderable: false,
        className: 'select-checkbox',
        targets: 0
      }],
      select: {
        style: 'os',
        selector: 'td:first-child'
      },
      order: [[ 1, 'asc' ]]
    });
  });
  // function filter(element, selector) {
  //   var value = $(element).val().toUpperCase();
  //   $(selector +" tr").each(function () {
  //     if ($(this).text().toUpperCase().indexOf(value)> -1) {
  //       $(this).show();
  //     } else {
  //       $(this).hide();
  //     }
  //   });
  // }

  // $('.search').keyup(function(){
  //   filter(this, '#table');
  // })
</script>

{% endblock js %}